# SMS Spam Detector
## Text Preprocessing & Feature Engineering

**Goal:** Clean raw text data and convert it into numerical features that our ML model can understand.

## 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Thusyya
[nltk_data]     Vardhan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## 2. Loading Cleaned Dataset

In [2]:
df = pd.read_csv('../data/spam_clean.csv')
print(df.shape)
df.head()

(5169, 5)

,label,message,length,word_count,label_enc
0,ham,"Go until jurong point, crazy.. Available only ...",111,20,0
1,ham,Ok lar... Joking wif u oni...,29,6,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,28,1
3,ham,U dun say so early hor... U c already then say...,49,11,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,13,0

## 3. Text Preprocessing

Raw text contains a lot of noise — punctuation, numbers, stopwords (like "the", "is", "a") that add no value for spam detection. We need to clean it before feeding it to our model.

Steps:
1. Lowercase the text
2. Remove punctuation and numbers
3. Remove stopwords
4. Stemming — reduce words to their root form (e.g. "calling", "called" → "call")

In [3]:
ps = PorterStemmer()

def preprocess(text):
    # 1. Lowercase
    text = text.lower()
    # 2. Remove punctuation and numbers
    text = re.sub(r'[^a-z\s]', '', text)
    # 3. Tokenize
    tokens = text.split()
    # 4. Remove stopwords and stem
    tokens = [ps.stem(w) for w in tokens if w not in stopwords.words('english')]
    return ' '.join(tokens)

In [4]:
# Test it on a sample message
sample = "Congratulations! You have WON a FREE prize. Call now at 98765!"
print("Before:", sample)
print("After:", preprocess(sample))

Before: Congratulations! You have WON a FREE prize. Call now at 98765!
After: congratul free prize call

## 4. Applying Preprocessing to Entire Dataset

In [5]:
df['processed'] = df['message'].apply(preprocess)
print("Preprocessing complete!")
df[['message', 'processed']].head(10)

Preprocessing complete!

,message,processed
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though
5,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey darl week word back id like fun st...
6,Even my brother is not like to speak with me. ...,even brother like speak treat like aid patent
7,As per your request 'Melle Melle (Oru Minnamin...,per request mell mell oru minnaminungint nurun...
8,WINNER!! As a valued network customer you have...,winner valu network custom select receivea pri...
9,Had your mobile 11 months or more? U R entitle...,mobil month u r entitl updat latest colour mob...

## 5. Saving Preprocessed Data

In [8]:
df.to_csv('../data/spam_processed.csv', index=False)
print("Processed data saved!")

Processed data saved!

In [9]:
df.head()

,label,message,length,word_count,label_enc,processed
0,ham,"Go until jurong point, crazy.. Available only ...",111,20,0,go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,29,6,0,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,28,1,free entri wkli comp win fa cup final tkt st m...
3,ham,U dun say so early hor... U c already then say...,49,11,0,u dun say earli hor u c alreadi say
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,13,0,nah dont think goe usf live around though